openapi: 3.0.0
info:
  contact:
    email: support@collaborativedrug.com
    name: BioAssay Express
    url: https://www.bioassayexpress.com
    x-id: https://www.collaborativedrug.com/
    x-role: responsible organization
  termsOfService: https://www.bioassayexpress.com/docs/license.jsp
  title: CDD BioAssay Express
  version: 1.0.7
servers:
- description: BioExpress server
  url: https://www.bioassayexpress.com/REST/
  x-location: Burlingame, California, USA
  x-maturity: production
paths:
  /GetAssay:
    get:
      description: Return BioAssay information with full annotation
      externalDocs:
        url: https://www.bioassayexpress.com/docs/
        x-description: The BioAssay Express is a web-based tool for annotating bioassay
          protocols using semantic web terms.
        x-type: publication
      operationId: getBAEassay
      parameters:
      - description: 'Assay Identifier'
        in: query
        name: assayID
        required: true
        schema:
          example: 101
          type: number
        x-parameterValueType:
          x-parameterType: bae.id
          x-valueType: http://identifiers.org/bioassay.bae
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assay'
          description: Assay model instance
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unable to find assayID
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get BioAssay information
      tags:
      - Assays
      x-accessRestriction: limited
      x-controller-name: Assays
      x-operation-name: GetAssay
  /GetPropertyList:
    post:
      description: Returns list of terms for specified ontology
      operationId: getBAEpropertyList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyQuery'
        description: A JSON object containing assay keywords
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropertyList'
          description: Term model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get ontology properties list
      tags:
      - Terms
      x-accessRestriction: limited
      x-controller-name: Terms
      x-operation-name: GetPropertyList
  /GetPropertyTree:
    post:
      description: Returns list of terms with tree for specified ontology
      operationId: getBAEpropertyTree
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyQuery'
        description: A JSON object containing assay keywords
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropertyTree'
          description: Term model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get ontology properties tree
      tags:
      - Terms
      x-accessRestriction: limited
      x-controller-name: Terms
      x-operation-name: GetPropertyTree
  /SelectionTree:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchemaURI'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SelectionTree'
                type: array
          description: Term model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      tags:
      - Terms
      summary: Get selection tree
  /KeywordMatch:
    post:
      description: Return assay terms matched by keywords
      operationId: getBAEassaysByKeyword
      requestBody:
        content:
          application/json:
            schema:
              example:
                annotations: []
                keywords: enzyme
                schemaURI: http://www.bioassayontology.org/bas#
                select: null
              properties:
                annotations:
                  items:
                    type: string
                  type: array
                keywords:
                  type: string
                schemaURI:
                  type: string
                select:
                  type: string
              required:
              - keywords
              - annotations
        description: A JSON object containing assay keywords
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Terms'
          description: Term model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get assay terms matched by keywords
      tags:
      - Terms
      x-accessRestriction: limited
      x-controller-name: Terms
      x-operation-name: KeywordMatch
  /ListCuratedAssays:
    get:
      description: Return a list of currated assays in BioAssay Express
      externalDocs:
        url: https://www.bioassayexpress.com/docs/
        x-description: The BioAssay Express is a web-based tool for annotating bioassay
          protocols using semantic web terms.
        x-type: publication
      operationId: getBAEcurratedAssaysList
      parameters:
      - description: Sort order
        in: query
        name: anomaly
        schema:
          enum:
          - blank
          - outschema
          type: string
      - description: Sort order
        in: query
        name: order
        schema:
          enum:
          - ascending
          - descending
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssaysList'
          description: Assay model instance
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get a list of curated BioAssays
      tags:
      - Assays
      x-accessRestriction: limited
      x-controller-name: Assays
      x-operation-name: ListCuratedAssays
  /ListCompounds:
    post:
      description: Returns list of compound IDs belonging to assays
      operationId: postBEAlistCompounds
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssayIDList'
        description: A JSON object containing list of assay IDs
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompoundList'
          description: Term model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get ontology properties list
      tags:
      - Compounds
      x-accessRestriction: limited
      x-controller-name: Compounds
      x-operation-name: ListCompounds
  /ListQueryAssays:
    post:
      description: Returns list of assays that match the query
      operationId: postBEAlistQueryAssays
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssayQuery'
        description: A JSON object containing list of assay IDs
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssayIDList'
          description: Assay IDs
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get list of matching assay
      tags:
      - Assays
      x-accessRestriction: limited
      x-controller-name: Assays
      x-operation-name: ListQueryAssays
  /DescribeSchema:
    post:
      description: Return the Schema information
      operationId: describeBAEschema
      requestBody:
        content:
          application/json:
            schema:
              example:
                locator: "12"
              properties:
                locator:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaValues'
          description: Schema model instances
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get schema information
      tags:
      - Schemas
      x-accessRestriction: limited
      x-controller-name: Schemas
      x-operation-name: DescribeSchema
components:
  schemas:
    Annotation:
      properties:
        groupLabel:
          items:
            type: string
          type: array
        groupNest:
          items:
            type: string
          type: array
        labelHier:
          items:
            type: string
          type: array
        outOfSchema:
          type: boolean
        propAbbrev:
          type: string
        propLabel:
          type: string
        propURI:
          type: string
        valueAbbrev:
          type: string
        valueDescr:
          type: string
        valueHier:
          items:
            type: string
          type: array
        valueLabel:
          type: string
        valueURI:
          type: string
      title: Annotation
    Assay:
      properties:
        annotations:
          items:
            $ref: '#/components/schemas/Annotation'
          type: array
        assayID:
          type: number
          x-responseValueType:
            x-path: ncbigene.id
            x-valueType: http://identifiers.org/ncbigene
        curationTime:
          type: number
        curatorID:
          type: string
        history:
          items:
            $ref: '#/components/schemas/Event'
          type: array
        holdingIDList:
          items:
            type: string
          type: array
        notes:
          type: string
        pubchemXRef:
          items:
            $ref: '#/components/schemas/pubchemXRef'
          type: array
        schemaURI:
          type: string
        text:
          type: string
        uniqueID:
          type: string
      required:
      - assayID
      title: Assay
    AssaysList:
      properties:
        assayIDList:
          items:
            type: number
          type: array
        curationTime:
          items:
            type: number
          type: array
        uniqueIDList:
          items:
            type: string
          type: array
      title: AssaysList
    AssayIDList:
      example:
        assayIDList: [1, 2, 3, 4]
      properties:
        assayIDlist:
          items:
            type: number
          type: array
      title: AssayIDList
    AssayReference:
      example:
        assayID: 1
        operator: "<"
        field: "EC50"
        threshold: 5
      properties:
        assayID:
          type: number
        operator:
          type: string
        field:
          type: string
        threshold:
          type: number
      title: AssayReference
    AssayQuery:
      example:
        query: '(propURI=bao:BAO_00012345)'
      properties:
        query:
          type: string
    CompoundList:
      example:
        compoundIDList: [1, 2, 3, 4, 5, 6]
        hashECFP6List: [1854422136, 1863941460, 638742098, 454877582, -25563370, -2002476729]
        assays:
          - assayID: 1
            operator: "<"
            field: "EC50"
            threshold: 5
        columns:
          - assayID: 1
            name: "Active/Inactive"
            units: "binary"
            type: "activity"
        measureIndex: [0, 0, 0, 0, 0, 0]
        measureCompound: [62582, 172500, 154584, 30669, 54928, 126160]
        measureValue: [1, 1, 0, 1, 0, 0]
        measureRelation: ["=", "=", "=", "=", "=", "="]
      properties:
        compoundIDList:
          items:
            type: number
          type: array
        hashECFP6List:
          items:
            type: number
          type: array
        assays:
          items:
            $ref: '#/components/schemas/AssayReference'
          type: array
        columns:
          items:
            $ref: '#/components/schemas/Column'
          type: array
        measureIndex:
          items:
            type: number
          type: array
        measureCompound:
          items:
            type: number
          type: array
        measureValue:
          items:
            type: number
          type: array
        measureRelation:
          items:
            type: string
          type: array
      title: CompoundList
    Column:
      example:
        assayID: 1
        name: "Active/Inactive"
        units: "binary"
        type: "activity"
      properties:
        assayID:
          type: number
        name:
          type: string
        units:
          type: string
        type:
          type: string
      title: Column
    Error:
      properties:
        developerMessage:
          type: string
        status:
          format: int32
          type: integer
        userMessage:
          type: string
      required:
      - status
      - userMessage
    Event:
      properties:
        annotsAdded:
          items:
            $ref: '#/components/schemas/Annotation'
          type: array
        annotsRemoved:
          items:
            $ref: '#/components/schemas/Annotation'
          type: array
        curationTime:
          type: number
        curatorID:
          type: string
        labelsAdded:
          items:
            $ref: '#/components/schemas/Label'
          type: array
        labelsRemoved:
          items:
            $ref: '#/components/schemas/Label'
          type: array
        notesModified:
          type: object
      title: Event
    Label:
      properties:
        propAbbrev:
          type: string
        propLabel:
          type: string
        propURI:
          type: string
        valueLabel:
          type: string
      title: Label
    PrefixMap:
      example:
        'az:': 'http://rdf.astrazeneca.com/bae#'
        'uo:': 'http://purl.org/obo/owl/UO#'
        'owl:': 'http://www.w3.org/2002/07/owl#'
        'src:': 'http://www.bioassayexpress.org/sources#'
        'bao:': 'http://www.bioassayontology.org/bao#'
        'bas:': 'http://www.bioassayontology.org/bas#'
        'xsd:': 'http://www.w3.org/2001/XMLSchema#'
        'bat:': 'http://www.bioassayontology.org/bat#'
        'obo:': 'http://purl.obolibrary.org/obo/'
        'rdfs:': 'http://www.w3.org/2000/01/rdf-schema#'
        'prov:': 'http://www.w3.org/ns/prov#'
        'taxon:': 'http://www.bioassayontology.org/taxon#'
        'protein:': 'http://www.bioassayontology.org/protein#'
        'geneid:': 'http://www.bioassayontology.org/geneid#'
        'rdf:': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
        'dto:': 'http://www.drugtargetontology.org/dto/'
        'bae:': 'http://www.bioassayexpress.org/bae#'
      properties:
       'az:':
         type: string
       'uo:': 
         type: string
       'owl:': 
         type: string
       'src:': 
         type: string
       'bao:': 
         type: string
       'bas:': 
         type: string
       'xsd:': 
         type: string
       'bat:': 
         type: string
       'obo:': 
         type: string
       'rdfs:': 
         type: string
       'prov:': 
         type: string
       'taxon:': 
         type: string
       'protein:': 
         type: string
       'geneid:': 
         type: string
       'rdf:': 
         type: string
       'dto:': 
         type: string
       'bae:': 
         type: string
    Property:
      properties:
        abbrev:
          type: string
        inModel:
          type: boolean
        inSchema:
          type: boolean
        name:
          type: string
        uri:
          type: string
      title: Property
    PropertyList:
      properties:
        list:
          items:
            $ref: '#/components/schemas/Property'
          type: array
      title: PropertyList
    PropertyQuery:
      example:
        groupNest: []
        propURI: http://www.bioassayontology.org/bao#BAO_0002854
        schemaBranches: null
        schemaURI: http://www.bioassayontology.org/bas#
      properties:
        groupNest:
          items:
            type: string
          type: array
        propURI:
          type: string
        schemaBranches:
          type: string
        schemaURI:
          type: string
      required:
      - propURI
    PropertyTree:
      properties:
        tree:
          type: object
          properties:
            depth:
              items:
                type: number
              type: array
            parent:
              items:
                type: number
              type: array
            name:
              items:
                type: string
              type: array
            abbrev:
              items:
                type: string
              type: array
            inSchema:
              items:
                type: boolean
              type: array
            schemaCount:
              items:
                type: number
              type: array
            childCount:
              items:
                type: number
              type: array
            inModel:
              items:
                type: boolean
              type: array
            altLabels:
              items:
                type: string
              type: array
            externalURLs:
              items:
                type: string
              type: array
            containers:
              items:
                type: number
              type: array
            prefixMap:
                $ref: '#/components/schemas/PrefixMap'
      title: PropertyTree
    PropertyURI:
      properties:
        propURI:
          type: string
        keywordSelector:
          type: string
        valueURIList:
          items:
            type: string
          type: array
        groupNest:
          items:
            type: string
          type: array
      title: PropertyURI
    SelectionTree:
      properties:
        treeList:
          items:
            type: number
          type: array
        literalList:
          items:
            type: string
          type: array
        matchesAssayID:
          items:
            type: number
          type: array
        matchesUniqueID:
          items:
            type: number
          type: array
      title: SelectionTree
    Schema:
      example:
        name: '100 percent growth inhibition'
        uri: 'http://www.bioassayontology.org/bao#BAO_0001108'
        abbrev: bao:BAO_0001108'
        descr: ''
        inSchema: true
        isExplicit: false
        hasModel: false
      properties:
        name:
          type: string
        uri:
          type: string
        abbrev:
          type: string
        descr:
          type: string
        inSchema:
          type: boolean
        isExplicit:
          type: boolean
        hasModel:
          type: boolean
      title: Schema
    SchemaURI:
      example:
        schemaURI: 'http://www.bioassayontology.org/bao#BAO_0001108'
        select: [{propURI: 'KEYWORD', keywordSelector: 'enzyme'}]
      properties:
        schemaURI:
         type: string
        select:
          items:
            $ref: '#/components/schemas/PropertyURI'
          type: array
      title: SchemaURI
    SchemaValues:
      properties:
        values:
          items:
            $ref: '#/components/schemas/Schema'
          type: array
      title: SchemaValues
    Term:
      properties:
        groupLabel:
          items:
            type: string
          type: array
        groupNest:
          items:
            type: string
          type: array
        propLabel:
          type: string
        propURI:
          type: string
        valueLabel:
          type: string
        valueURI:
          type: string
      title: Term
    Terms:
      properties:
        terms:
          items:
            $ref: '#/components/schemas/Term'
          type: array
      title: Terms
    pubchemXRef:
      properties:
        comment:
          type: string
        id:
          type: string
        type:
          type: string
      title: pubchemXRef
